ARG BASE_IMAGE=public.ecr.aws/lambda/python:3.9
FROM $BASE_IMAGE


# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.lambda_handler" ]