# This is a basic workflow to help you get started with Actions

name: caller

# Controls when the workflow will run
on:
  push:
    paths:
      - template.yaml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow:
    uses: ./.github/workflows/called.yml
    with:
      username: mona
  call-workflow-2:
    needs: call-workflow
    uses: ./.github/workflows/called.yml
    with:
      username: dion
