# This is a basic workflow to help you get started with Actions

name: caller

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow:
    uses: fachid/githubActions/edit/main/.github/workflows/called.yml@main
    with:
      username: mona


       

