name: globalEnv

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  var: testVar

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo $GITHUB_ENV
          ls -la $GITHUB_ENV
          chmod 777  $GITHUB_ENV
          ls -la $GITHUB_ENV
          ls -la $GITHUB_ENV/../
          cat $GITHUB_ENV
          echo ${{ env.var }}
          echo "var=changedTestVar" >> $GITHUB_ENV


  second:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: first

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ env.var }}
