name: input

on:
  push:

  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS_ACCESS_KEY_ID_IN'
        required: true
        default: '-'
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS_SECRET_ACCESS_KEY_IN'
        required: true
        default: '-'
      AWS_DEFAULT_REGION:
        description: 'AWS_DEFAULT_REGION_IN'
        required: true
        default: 'us-east-1'
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'        


jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from secrets
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ github.event.inputs.AWS_ACCESS_KEY_ID == '' }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        
    - name: Configure AWS credentials from inputs 
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ github.event.inputs.AWS_ACCESS_KEY_ID != '' }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}        
    
    - name: Execute      
      env:
        REGION: ${{ github.event.inputs.region}}
      run: |
        echo "ok"
        echo "$REGION"
        aws sts get-caller-identity | jq -r '.Account' 
