name: Input

on:
  push:

  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID_IN:
        description: 'AWS_ACCESS_KEY_ID'
        required: true
        default: '-'
      AWS_SECRET_ACCESS_KEY_IN:
        description: 'AWS_SECRET_ACCESS_KEY'
        required: true
        default: '-'
      AWS_SESSION_TOKEN_IN:
        description: 'AWS_SESSION_TOKEN'
        required: true
        default: '-'          
      AWS_DEFAULT_REGION_IN:
        description: 'AWS_DEFAULT_REGION'
        required: true
        default: 'us-east-1'
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'        


jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from secrets
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ github.event.inputs.AWS_ACCESS_KEY_ID_IN == '' }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        
    - name: Configure AWS credentials from inputs 
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ github.event.inputs.AWS_ACCESS_KEY_ID_IN != '' }}
      with:
        aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID_IN }}
        aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY_IN }}
        aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN_IN }}           
        aws-region: ${{ github.event.inputs.AWS_DEFAULT_REGION_IN }}  
     
    
    - name: Execute      
      env:
        REGION: ${{ github.event.inputs.region}}
      run: |
        echo "ok"
        echo "$REGION"
        aws sts get-caller-identity | jq -r '.Account' 
        aws s3 ls
