name: matrix

on:
  workflow_dispatch:

jobs:
  createMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.values }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=values::[{"a","b","c"}]"

  my_echo:
    runs-on: ubuntu-latest
    needs:
      - createMatrix
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.createMatrix.outputs) }}"


  builder:
    needs: my_echo
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        values: needs.createMatrix.outputs.values 
        #cfg: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: |
        echo bin-${{ matrix.values }}