name: matrix

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'api_docs function Image URI'
        default: ''

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        image: ${{ github.event.inputs.Environment }}
    runs-on: ubuntu-latest
#    env:
#      JDK_VERSION:  ${{ matrix.jdk }}



    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ matrix.image }}
 #         echo "usernam = ${{ inputs.username }}"
 #         echo "called workflow test, and deploy your project."