name: matrix

on:
  workflow_dispatch:

jobs:
  createMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.test }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=test::["a","b","c"]"

  builder:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: job1.outputs.matrix
        #cfg: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: |
        echo bin-${{ matrix.test }}