# This is a basic workflow to help you get started with Actions

name: multiEnv

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: envitonemnt
        options:
        - dev
        - test
        - prod 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

# $(if [ github.ref_name == main ]; then echo test; else echo dev; fi )
#     environment: test-${{ github.ref_name }}
#     environment: dion

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ github.event.inputs.environment }}
          echo -n "environemnt:"
          echo ${{ secrets.ENV }}
          echo ${{ secrets.ENV }} | sed -e 's/\(.\)/\1 /g'
