name: multi-job-artifact

on:
  push:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID_IN:
        description: 'AWS_ACCESS_KEY_ID'
        required: true
        default: '-'   

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - run: mkdir -p artifact

    - run: touch artifact/world.txt    

    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: artifact    
        
  job1:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: artifact

    - run: echo hello1 >> artifact/world.txt    

    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: artifact    
    
    
  job2:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: artifact

    - run: echo hello2 >> artifact/world.txt    
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: artifact        
        
        
        
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2] 
    env:
      TRIGGER: "aa"

    steps:
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: artifact

    - run: cat artifact/world.txt     
