# This is a basic workflow to help you get started with Actions

name: tagRelease

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/RC*') || startsWith(github.ref, 'refs/tags/V*') }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
          echo "RC_TAG=${{ github.ref_name }}" >> $GITHUB_ENV  
          
          VERSION_TAG=`git tag -l | sort -V | grep V | tail -n 1`

          if [  x"$VERSION_TAG" == x ]; then
            VERSION_TAG=V1
          else
            version=${VERSION_TAG#V}
            VERSION_TAG=V$((version+1))
          fi

          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV            
          
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: Release ${{ env.VERSION_TAG }}
          body: |
            Release ${{ env.VERSION_TAG }} created from ${{ env.RC_TAG }} Tag
          draft: false
          prerelease: false        

