# This is a basic workflow to help you get started with Actions

name: variable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:

      AppName:
        description: 'Application name'
        required: true
        default: 'sbx-1-ias-clear'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: setVariable
        run: |
          echo "Hello, world!"
          echo "##[set-output name=test_secret;]$(echo ${{ secrets.TEST_SERCRET }})"
          echo "DION=yellow" >> $GITHUB_ENV



      - name: Run a one-line script
        run: |
          echo ${{ steps.setVariable.outputs.test_secret }}
          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_REF_NAME}
          echo ${GITHUB_ACTION}
          echo ${DION}
          echo "DION=GREEN" >> $GITHUB_ENV
          echo "APP_NAME=${{ github.event.inputs.AppName }}" >> $GITHUB_ENV
          

      - name: Run a one-line script
        #if: ${{ github.event.inputs.AWS_ACCESS_KEY_ID_IN != '' }}
        run: |       
          if [ $APP_NAME == "DION" ]
          then
          echo Hey that\'s a large number.
          echo ${DION}
          pwd
          fi
          

          
