name: yq

on:
  # push:
  #   branches:
  #     - test
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID_IN:
        description: 'AWS_ACCESS_KEY_ID'
        required: true
        default: '-'
      AWS_SECRET_ACCESS_KEY_IN:
        description: 'AWS_SECRET_ACCESS_KEY'
        required: true
        default: '-'
      AWS_SESSION_TOKEN_IN:
        description: 'AWS_SESSION_TOKEN'
        required: true
        default: '-'          
      AWS_DEFAULT_REGION_IN:
        description: 'AWS_DEFAULT_REGION'
        required: true
        default: 'us-east-1'
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'        


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      TRIGGER: "aa"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    
    - name: Execute      
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        yq --version
