name: yq

on:
  # push:
  #   branches:
  #     - test
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      TRIGGER: "aa"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    
    - name: Execute      
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        yq --version
        yq e '.Resources[] | select( .Type == "AWS::S3::Bucket" )' enterpriseHLT-stack.yaml
